

// colors={['#b2e8e9', '#006F9C', '#045D99']}
export const colors = {
  transparent: 'transparent',
  light: '#f0f0f0',
  grey0: '#393e42',
  grey1: '#43484d',
  grey2: '#5e6977',
  grey3: '#86939e',
  grey4: '#bdc6cf',
  grey5: '#e1e8ee',
  grey6: '#fafbfc',
  grey7: '#E9EBF2',
  gray: '#8C8C8C',
  gray1: '#BFBFBF',
  gray2: '#E6E7E9',
  gray3: '#E8E8E8',
  gray4: '#99A0B0',
  white: '#FFFFFF',
  white1: '#D9D9D9',
  white2: '#F5F5F5',
  white3: '#eef7fe',
  black: '#333333',
  black1: '#262626',
  black2: '#595959',
  black_transparent: 'rgba(0,0,0,0.25)',
  green: '#2EB553',
  green1: '#4DD077',
  green2: '#8CE1A7',
  yellow: '#FFEC3D',
  yellow1: '#FFF566',
  yellow2: '#FFFB8F',
  purple: '#722ED1',
  purple1: '#9254DE',
  purple2: '#B37FEB',
  blue: '#4D89FF',
  blue1: '#69C0FF',
  blue2: '#91D5FF',
  blue3: '#BAE7FF',
  lightblue: '#F1F6FF',
  lightblue1: '#1890FF',
  cyan: '#13C2C2',
  cyan1: '#36CFC9',
  cyan2: '#5CDBD3',
  red: '#F5222D',
  red1: '#FF4D4F',
  red2: '#FF7875',
  red3: '#FFA39E',
  orange: '#FA8C16',
  orange1: '#FFA940',
  orange2: '#FFC069',
  orange3: '#FF9C6E',
  orange4: '#FFBB96',
  orange5: '#FFD8BF',
  gray_blur: "#97a0a8",
  blue_black: "#001026",
  pink: "#ffb6f0",
  gray_blue: "#eaeef7",
  gradient_from_background: "#fdfdfd",
  gradient_end_background: "#d0dff2",
  gradient_from_button: "#8d70a8",
  gradient_end_button: "#e8599b",
  line: "#c3ccd5",
  forgot_color: '#9f5394',
  background_drawer: '#f0f8ff',
  yellow_contract: '#f2bd37',
  blue_contract: '#00aeef',
  green_contract: '#a1a1a1',
  gray_contract: '#a378b0',
  color_calendar: '#e8eff7',
  coral: '#ff7f50',
  thistle: '#d8bfd8',
  palevioletred: '#db7093',
  deepCerulean: '#03889A',
  easternBlue: '#22A6A0',
  allports: "#006F9C",
  milanoRed: '#B3110D',
  grayApprox: '#888888',
  dodgerBlue: '#1ECDFF',
  persianBlue: '#4021D0',
  geyser: '#DBE3E6',
  tangaroa: '#02083D',
  manatee: '#8B8C9B',
  mirage: '#191A2A',
  vulcan: '#141523',
  whisper: '#F8F7FA',
  mountainMeadow: '#12B886',
  athensGray: '#F9F9FB',
  linkWater: '#EEF2FA',
  ebonyClay: '#1F2131',
  ebonyClay2: '#2A283F',
  portage: '#8B82EF',
  mirageB: "#191B2B",
  ghost: '#C8C7D6',
  scarpaFlow: '#555459',
  blackSqueeze: '#F5F9FC',
  dullLavender: '#9D92E1',
  arapawa: '#1D0E6B',
  cornflowerBlue: '#7658FF',
  royalBlue: '#5547F4'
};

export const colorDefaultTheme: ThemeColors = {
  // COLORS VIEW
  backgroundGlobal: colors.white,
  backgroundCard: colors.white,
  line: colors.whisper,
  backgroundItem: colors.white,
  backgroundCardSignal: colors.white,
  backgroundButton: colors.persianBlue,
  backgroundLogOutButton: colors.whisper,
  backgroundSwapButton: colors.dullLavender,
  backgroundButtonCard: colors.whisper,
  backgroundExchange: colors.blackSqueeze,
  backgroundWallet: colors.arapawa,
  focusTopTab: colors.persianBlue,

  //COLOR BORDER
  borderColorCard: colors.linkWater,


  //COLORS TITLE
  heading: colors.tangaroa,
  textDesc: colors.manatee,
  textIncrease: colors.mountainMeadow,
  textUtilities: colors.tangaroa,
  textSignalStatus: colors.white,
  textViewAll: colors.persianBlue,
  textCard: colors.tangaroa,
  textColorButton: colors.white,
  textHeader: colors.black,
  textTitleMenu: colors.manatee,
  labelButtonColor: colors.scarpaFlow,
  labelSwap: colors.white,
  buttonWallet: colors.cornflowerBlue,
  textNameCoin: colors.mirageB

}
export const colorDarkTheme: ThemeColors = {
  ...colorDefaultTheme,

  //COLORS VIEW DARK 
  // backgroundGlobal: colors.vulcan,
  backgroundGlobal: colors.blue_black,
  // backgroundCard: colors.blue_black,
  backgroundCard: colors.blue_black,
  line: colors.mirage,
  backgroundItem: colors.mirage,
  backgroundCardSignal: colors.ebonyClay,
  backgroundButton: colors.persianBlue,
  backgroundLogOutButton: colors.mirageB,
  backgroundSwapButton: colors.ebonyClay2,
  backgroundButtonCard: colors.mirageB,
  backgroundExchange: colors.vulcan,
  backgroundWallet: colors.vulcan,
  focusTopTab: colors.white,

  //COLOR BORDER
  borderColorCard: colors.transparent,

  //COLORS TITLE DARK
  heading: colors.geyser,
  textDesc: colors.manatee,
  textIncrease: colors.mountainMeadow,
  textUtilities: colors.geyser,
  textSignalStatus: colors.white,
  textViewAll: colors.portage,
  textCard: colors.geyser,
  textColorButton: colors.white,
  textHeader: colors.white,
  textTitleMenu: colors.ghost,
  labelButtonColor: colors.manatee,
  labelSwap: colors.geyser,
  buttonWallet: colors.royalBlue,
  textNameCoin: colors.whisper

}