export const screenName = {
  HOME: "Home",
  COMING_SOON: 'Coming soon',
  MARKET: "Market",
  NOTIFY: "Notify",
  NOTIFICATIONS: "Notifications",
  EXCHANGE: "Exchange",
  WALLET: "Wallet",
  SIGNAL: "Signal",
  MENU: 'Menu',
  BOTTOM_TABS: 'Bottom Tabs',
  REFERRER: 'Referrer',
  TRADING_VIEW: "Trading View",
  CHANGE_PASSWORD: "Change Password",
  REGISTER: "Register",
  LOGIN_DEFAULT: 'Login Default',
  FORGOT_PASSWORD: "Forgot Password",
  HISTORY: "History",
  HISTORY_DETAIL: "History Detail"
}